### PR TITLE
simplify code contributions by fully automating the dev setup

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! 

This Pr simplifies code contributions by fully automating the dev setup with Gitpod(an online VS-Code like IDE). With a single click, it'll launch a workspace and automatically:

- clone the 98.css repo.
- install the dependencies.
- run `npm run build`
- start the webserver.

so that anyone interested in contributing can start straight away without any friction.

image
 
You can give it a try on my fork of the repo via the following link:

https://gitpod.io/#https://github.com/nisarhassan12/98.css

### CODE REVIEW

**Comment by jdan** [comment]
Hi! I'm not interested in including an additional yaml here unless I'm personally using the tool. Definitely consider reading from `package.json` automatically in your product though.

**Comment by nisarhassan12** [comment]
Sure, fair enough. Also, reading from package.json automatically is a great idea, thanks for the suggestion!

Meanwhile I'll add this configuration to Gitpod's [external config repo](https://github.com/gitpod-io/definitely-gp), so that your project's dev setup is still fully-automated when you open it in Gitpod. I hope that's cool with you?

**Comment by jdan** [comment]
Fine with me :)

**Comment by nisarhassan12** [comment]
Thanks.

**Pull request closed without merging**
