### PR TITLE
Add Component ProgressBar

### PR DESCRIPTION
**Pull request by pedrobonifacio**
I created a class that can be given to a div, the div will contain a span, see the example:
```html
<div class="meter"> 
    <span style="width: 80%"></span> 
</div>
```
result:
ProgressBar

### CODE REVIEW

**Comment by JuanGaray93** [comment]
Hi, Pedro! You seem to have deleted the documentation for dropdowns. Could you restore it?

**Comment by JuanGaray93** [comment]
The bar shows incomplete squares (I'm viewing this in Firefox). Can you think of any way to cut squares off? 

image

**Comment by warpcoil** [comment]
The cut squares issue can be fixed with CSS rounding.  I have found a way but it's not perfect.  I've also merged a few fixes from another fork and re-added the original drop down documentation.

You can refer to the pull request here:

[Whole Progress Squares](https://github.com/PlanMan1717/98.css/pull/1)

Regards

Bobby

**Comment by its-pablo** [comment]
Any ETA for merging this PR

**Comment by juanigaray** [comment]
Closing this PR as it's become stale. I've used a commit from this branch to create a new PR with a few changes. Feel free to give feedback on my PR!

**Pull request closed without merging**
