### PR TITLE
Further input type styling

### PR DESCRIPTION
**Pull request by xHeinrich**
Input styling for password and email types, without this the inputs are basically unstyled.

Examples:
```html
<div class="field-row">
    <label for="email" style="width: 80px;">Email:</label>
    <input id="email" type="email" name="email" value="" required autocomplete="email" autofocus>
</div>
<div class="field-row">
    <label for="password" style="width: 80px;">Email:</label>
    <input id="password" type="password" name="password" value="" required>
</div>
```

With:
image
Without:

image

### CODE REVIEW

**Comment by jdan** [comment]
Thanks for this :)

Our CI setup is a bit wonky, but could you run `npm run build` and commit those changes? This way we'll see your changes on the docs site.

**Comment by xHeinrich** [comment]
Done :)

**Comment by jdan** [comment]
@xHeinrich Are you on windows? I was mucking with line-endings earlier, but this should be using LFs now :)

Wanna rebase off master? I also added an `.editorconfig` so your IDE may read it and use LF.

**Comment by xHeinrich** [comment]
@jdan yep windows. I'll close this one and re-open with a different branch.

**Pull request closed without merging**
