### PR TITLE
Add input[type="tel"] to format phone inputs

### PR DESCRIPTION
**Pull request by dsgibbons**
Add input[type="tel"] to format phone inputs

### CODE REVIEW

**Comment by juanigaray** [comment]
This looks good! What do you think abt adding an input with type="tel" to the end of the [TextBox section](https://98css-gvl97q9bt-jdan.vercel.app/#text-box)?

**Comment by dsgibbons** [comment]
I'm not quite sure what you mean (I'm a CSS novice). How is this different from textarea? Can you provide a reference to the line in styles.css?

**Comment by juanigaray** [comment]
> I'm not quite sure what you mean (I'm a CSS novice). How is this different from textarea? Can you provide a reference to the line in styles.css?

I mean adding it to the HTML as an additional example! Here
image

**Comment by dsgibbons** [comment]
> I mean adding it to the HTML as an additional example! Here

Ah I see! Example added

**Comment by juanigaray** [comment]
Thank you!!

**Pull request merged**
